name: plummbur_kruk
version: 0.1.1
description: A real pretend server for testing.
author: Chris Strom <chris@eeecomputes.com>
homepage: https://github.com/eee-c/plummbur-kruk
dependencies:
  dirty: ">=0.1.3 <0.1.4"
  browser: ">=0.9.0 < 0.10.0"
  uuid: ">=0.1.6 <0.1.7"
  ansicolor: ">=0.0.9 <0.0.10"
  intl: ">=0.9.0 <0.9.1"
dev_dependencies:
  scheduled_test: any
