name: plummbur_kruk
version: 0.0.1
description: A real pretend server for testing.
author: Chris Strom <chris@eeecomputes.com>
homepage: https://github.com/eee-c/plummbur-kruk
dependencies:
  scheduled_test: any
  dirty: any
  uuid: any
